/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddClinicResponsibleRequest } from './models/AddClinicResponsibleRequest';
export type { AddDepartmentResponsibleRequest } from './models/AddDepartmentResponsibleRequest';
export type { AddOrganizationCategoryResponsibleRequest } from './models/AddOrganizationCategoryResponsibleRequest';
export type { AddOrganizationResponsibleRequest } from './models/AddOrganizationResponsibleRequest';
export type { AddResponsibleRequest } from './models/AddResponsibleRequest';
export type { Address } from './models/Address';
export type { AssignDepartmentEmployeeRequest } from './models/AssignDepartmentEmployeeRequest';
export type { BusinessRuleViolationDetails } from './models/BusinessRuleViolationDetails';
export type { Category } from './models/Category';
export type { CategoryBrief } from './models/CategoryBrief';
export type { CategoryCandidateIneligibilityReason } from './models/CategoryCandidateIneligibilityReason';
export { CategoryCandidateIneligibilityReasonCode } from './models/CategoryCandidateIneligibilityReasonCode';
export type { CategoryCandidateIneligibilityReasonCodes } from './models/CategoryCandidateIneligibilityReasonCodes';
export type { CategoryId } from './models/CategoryId';
export type { CategoryListResponse } from './models/CategoryListResponse';
export type { CategoryResponsibleListResponse } from './models/CategoryResponsibleListResponse';
export type { Clinic } from './models/Clinic';
export type { ClinicBrief } from './models/ClinicBrief';
export type { ClinicEmployee } from './models/ClinicEmployee';
export type { ClinicEmployeeListResponse } from './models/ClinicEmployeeListResponse';
export type { ClinicId } from './models/ClinicId';
export type { ClinicListResponse } from './models/ClinicListResponse';
export type { ConflictErrorDetails } from './models/ConflictErrorDetails';
export type { CreateCategoryRequest } from './models/CreateCategoryRequest';
export type { CreateClinicRequest } from './models/CreateClinicRequest';
export type { CreateClinicResponse } from './models/CreateClinicResponse';
export type { CreateDepartmentRequest } from './models/CreateDepartmentRequest';
export type { CreateDepartmentResponse } from './models/CreateDepartmentResponse';
export type { CreateEventCategoryResponse } from './models/CreateEventCategoryResponse';
export type { CreateEventTypeRequest } from './models/CreateEventTypeRequest';
export type { CreateEventTypeResponse } from './models/CreateEventTypeResponse';
export type { CreateOrganizationRequest } from './models/CreateOrganizationRequest';
export type { CreateOrganizationResponse } from './models/CreateOrganizationResponse';
export type { Cursor } from './models/Cursor';
export type { CursorPagination } from './models/CursorPagination';
export { DayOfWeek } from './models/DayOfWeek';
export type { Department } from './models/Department';
export type { DepartmentBrief } from './models/DepartmentBrief';
export type { DepartmentEmployee } from './models/DepartmentEmployee';
export type { DepartmentEmployeeListResponse } from './models/DepartmentEmployeeListResponse';
export type { DepartmentId } from './models/DepartmentId';
export type { DepartmentListResponse } from './models/DepartmentListResponse';
export type { Employment } from './models/Employment';
export type { EnableOrganizationCategoryRequest } from './models/EnableOrganizationCategoryRequest';
export type { Error } from './models/Error';
export type { ErrorDetails } from './models/ErrorDetails';
export type { EventType } from './models/EventType';
export type { EventTypeCategoryId } from './models/EventTypeCategoryId';
export type { EventTypeListResponse } from './models/EventTypeListResponse';
export type { EventTypePatientCanReport } from './models/EventTypePatientCanReport';
export type { ForbiddenErrorDetails } from './models/ForbiddenErrorDetails';
export type { GeoPoint } from './models/GeoPoint';
export type { GetClinicByIdResponse } from './models/GetClinicByIdResponse';
export type { GetDepartmentByIdResponse } from './models/GetDepartmentByIdResponse';
export type { GetEventCategoryByIdResponse } from './models/GetEventCategoryByIdResponse';
export type { GetEventTypeByIdResponse } from './models/GetEventTypeByIdResponse';
export type { GetMeResponse } from './models/GetMeResponse';
export type { GetMyNotificationSettingsResponse } from './models/GetMyNotificationSettingsResponse';
export type { GetOrganizationByIdResponse } from './models/GetOrganizationByIdResponse';
export type { GetUserByIdResponse } from './models/GetUserByIdResponse';
export type { IncludeDeactivated } from './models/IncludeDeactivated';
export type { IncludeIneligible } from './models/IncludeIneligible';
export type { IneligibilityReason } from './models/IneligibilityReason';
export { IneligibilityReasonCode } from './models/IneligibilityReasonCode';
export type { IneligibilityReasonCodes } from './models/IneligibilityReasonCodes';
export { InheritedFromSource } from './models/InheritedFromSource';
export type { Limit } from './models/Limit';
export type { ListClinicDepartmentsResponse } from './models/ListClinicDepartmentsResponse';
export type { ListClinicEmployeesResponse } from './models/ListClinicEmployeesResponse';
export type { ListClinicResponsibleCandidatesResponse } from './models/ListClinicResponsibleCandidatesResponse';
export type { ListClinicResponsiblesResponse } from './models/ListClinicResponsiblesResponse';
export type { ListDepartmentEmployeesResponse } from './models/ListDepartmentEmployeesResponse';
export type { ListDepartmentResponsibleCandidatesResponse } from './models/ListDepartmentResponsibleCandidatesResponse';
export type { ListDepartmentResponsiblesResponse } from './models/ListDepartmentResponsiblesResponse';
export type { ListEventCategoriesResponse } from './models/ListEventCategoriesResponse';
export type { ListEventCategoryTypesResponse } from './models/ListEventCategoryTypesResponse';
export type { ListEventTypesResponse } from './models/ListEventTypesResponse';
export type { ListOrganizationCategoriesResponse } from './models/ListOrganizationCategoriesResponse';
export type { ListOrganizationCategoryCandidatesResponse } from './models/ListOrganizationCategoryCandidatesResponse';
export type { ListOrganizationCategoryResponsibleCandidatesResponse } from './models/ListOrganizationCategoryResponsibleCandidatesResponse';
export type { ListOrganizationCategoryResponsiblesResponse } from './models/ListOrganizationCategoryResponsiblesResponse';
export type { ListOrganizationClinicsResponse } from './models/ListOrganizationClinicsResponse';
export type { ListOrganizationEmployeesResponse } from './models/ListOrganizationEmployeesResponse';
export type { ListOrganizationResponsibleCandidatesResponse } from './models/ListOrganizationResponsibleCandidatesResponse';
export type { ListOrganizationResponsiblesResponse } from './models/ListOrganizationResponsiblesResponse';
export type { ListOrganizationsResponse } from './models/ListOrganizationsResponse';
export type { ListUsersResponse } from './models/ListUsersResponse';
export type { NotFoundErrorDetails } from './models/NotFoundErrorDetails';
export { NotificationChannel } from './models/NotificationChannel';
export { NotificationEventType } from './models/NotificationEventType';
export type { NotificationQuietHours } from './models/NotificationQuietHours';
export type { NotificationRule } from './models/NotificationRule';
export type { NotificationSchedule } from './models/NotificationSchedule';
export type { NotificationSettings } from './models/NotificationSettings';
export type { Organization } from './models/Organization';
export type { OrganizationBrief } from './models/OrganizationBrief';
export type { OrganizationCategoryAllocation } from './models/OrganizationCategoryAllocation';
export type { OrganizationCategoryCandidate } from './models/OrganizationCategoryCandidate';
export type { OrganizationCategoryCandidateListResponse } from './models/OrganizationCategoryCandidateListResponse';
export type { OrganizationCategoryListResponse } from './models/OrganizationCategoryListResponse';
export type { OrganizationEmployee } from './models/OrganizationEmployee';
export type { OrganizationEmployeeListResponse } from './models/OrganizationEmployeeListResponse';
export type { OrganizationId } from './models/OrganizationId';
export type { OrganizationListResponse } from './models/OrganizationListResponse';
export type { ResponsibleCandidate } from './models/ResponsibleCandidate';
export type { ResponsibleCandidateListResponse } from './models/ResponsibleCandidateListResponse';
export type { ResponsibleListResponse } from './models/ResponsibleListResponse';
export type { ResponsibleUserId } from './models/ResponsibleUserId';
export type { ResponsibleWithSource } from './models/ResponsibleWithSource';
export type { SearchText } from './models/SearchText';
export type { TypeId } from './models/TypeId';
export type { UnauthorizedErrorDetails } from './models/UnauthorizedErrorDetails';
export type { UpdateCategoryRequest } from './models/UpdateCategoryRequest';
export type { UpdateClinicRequest } from './models/UpdateClinicRequest';
export type { UpdateDepartmentRequest } from './models/UpdateDepartmentRequest';
export type { UpdateEventTypeRequest } from './models/UpdateEventTypeRequest';
export type { UpdateMyNotificationSettingsRequest } from './models/UpdateMyNotificationSettingsRequest';
export type { UpdateOrganizationRequest } from './models/UpdateOrganizationRequest';
export type { UpdateUserDisplayNameRequest } from './models/UpdateUserDisplayNameRequest';
export type { User } from './models/User';
export type { UserBrief } from './models/UserBrief';
export type { UserId } from './models/UserId';
export type { UserListResponse } from './models/UserListResponse';
export type { UserNameBrief } from './models/UserNameBrief';
export type { UserNameFields } from './models/UserNameFields';
export type { ValidationErrorDetails } from './models/ValidationErrorDetails';
export type { ValidationErrorFieldDetail } from './models/ValidationErrorFieldDetail';

export { ClinicsService } from './services/ClinicsService';
export { DepartmentsService } from './services/DepartmentsService';
export { EventsService } from './services/EventsService';
export { OrganizationsService } from './services/OrganizationsService';
export { UsersService } from './services/UsersService';
