services:
  nextjs:
    image: ghcr.io/medincident/medincident-staff-frontend:latest
    container_name: nextjs_app
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      com.centurylinklabs.watchtower.scope: "medincident-staff-frontend"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx_gateway
    restart: unless-stopped
    ports:
      - "8083:80"
    networks:
      - default
      - proxy-network
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro
    environment:
      DOCKER_API_VERSION: "1.40"
      WATCHTOWER_SCOPE: "medincident-staff-frontend"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_POLL_INTERVAL: "60"
      WATCHTOWER_INCLUDE_RESTARTING: "true"
      TZ: "Europe/Moscow"

networks:
  proxy-network:
    external: true
