/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AnnouncementCommandServiceUpdateAnnouncementBody } from './models/AnnouncementCommandServiceUpdateAnnouncementBody';
export type { AnnouncementCommandServiceUpdateAnnouncementPriorityBody } from './models/AnnouncementCommandServiceUpdateAnnouncementPriorityBody';
export type { classifierV1Type } from './models/classifierV1Type';
export { commandAnnouncementV1AnnouncementPriority } from './models/commandAnnouncementV1AnnouncementPriority';
export { commandIncidentV1IncidentPriority } from './models/commandIncidentV1IncidentPriority';
export { commandIncidentV1IncidentStatus } from './models/commandIncidentV1IncidentStatus';
export type { IncidentBufferCommandServicePublishPatientIncidentBody } from './models/IncidentBufferCommandServicePublishPatientIncidentBody';
export type { IncidentBufferCommandServiceUpdatePatientIncidentBody } from './models/IncidentBufferCommandServiceUpdatePatientIncidentBody';
export type { IncidentClassifierCommandServiceCreateIncidentCategoryBody } from './models/IncidentClassifierCommandServiceCreateIncidentCategoryBody';
export type { IncidentClassifierCommandServiceCreateIncidentTypeBody } from './models/IncidentClassifierCommandServiceCreateIncidentTypeBody';
export type { IncidentClassifierCommandServiceMoveIncidentCategoryBody } from './models/IncidentClassifierCommandServiceMoveIncidentCategoryBody';
export type { IncidentClassifierCommandServiceMoveIncidentTypeBody } from './models/IncidentClassifierCommandServiceMoveIncidentTypeBody';
export type { IncidentClassifierCommandServiceUpdateIncidentCategoryDetailsBody } from './models/IncidentClassifierCommandServiceUpdateIncidentCategoryDetailsBody';
export type { IncidentClassifierCommandServiceUpdateIncidentTypeDetailsBody } from './models/IncidentClassifierCommandServiceUpdateIncidentTypeDetailsBody';
export type { IncidentCommandServiceUpdateIncidentDescriptionBody } from './models/IncidentCommandServiceUpdateIncidentDescriptionBody';
export type { IncidentCommandServiceUpdateIncidentPriorityBody } from './models/IncidentCommandServiceUpdateIncidentPriorityBody';
export type { IncidentCommandServiceUpdateIncidentStatusBody } from './models/IncidentCommandServiceUpdateIncidentStatusBody';
export type { MembershipCommandServiceAssignClinicHeadBody } from './models/MembershipCommandServiceAssignClinicHeadBody';
export type { MembershipCommandServiceAssignClinicHeadDeputyBody } from './models/MembershipCommandServiceAssignClinicHeadDeputyBody';
export type { MembershipCommandServiceAssignDepartmentResponsibleBody } from './models/MembershipCommandServiceAssignDepartmentResponsibleBody';
export type { MembershipCommandServiceAssignDepartmentResponsibleDeputyBody } from './models/MembershipCommandServiceAssignDepartmentResponsibleDeputyBody';
export type { MembershipCommandServiceAssignOrganizationAdminBody } from './models/MembershipCommandServiceAssignOrganizationAdminBody';
export type { MembershipCommandServiceAssignOrganizationAdminDeputyBody } from './models/MembershipCommandServiceAssignOrganizationAdminDeputyBody';
export type { MembershipCommandServiceAssignOrganizationDispatcherBody } from './models/MembershipCommandServiceAssignOrganizationDispatcherBody';
export type { MembershipCommandServiceAssignOrganizationDispatcherDeputyBody } from './models/MembershipCommandServiceAssignOrganizationDispatcherDeputyBody';
export type { MembershipCommandServiceAssignOrganizationHeadBody } from './models/MembershipCommandServiceAssignOrganizationHeadBody';
export type { MembershipCommandServiceAssignOrganizationHeadDeputyBody } from './models/MembershipCommandServiceAssignOrganizationHeadDeputyBody';
export type { MembershipCommandServiceScheduleVacationBody } from './models/MembershipCommandServiceScheduleVacationBody';
export type { MembershipCommandServiceStartVacationNowBody } from './models/MembershipCommandServiceStartVacationNowBody';
export type { MembershipCommandServiceUpdateEmployeeDepartmentBody } from './models/MembershipCommandServiceUpdateEmployeeDepartmentBody';
export type { MembershipCommandServiceUpdateEmployeePositionBody } from './models/MembershipCommandServiceUpdateEmployeePositionBody';
export type { MembershipCommandServiceUpdateVacationEndDateBody } from './models/MembershipCommandServiceUpdateVacationEndDateBody';
export type { OrgStructureCommandServiceCreateClinicBody } from './models/OrgStructureCommandServiceCreateClinicBody';
export type { OrgStructureCommandServiceCreateDepartmentBody } from './models/OrgStructureCommandServiceCreateDepartmentBody';
export type { OrgStructureCommandServiceUpdateClinicDetailsBody } from './models/OrgStructureCommandServiceUpdateClinicDetailsBody';
export type { OrgStructureCommandServiceUpdateClinicPhysicalAddressBody } from './models/OrgStructureCommandServiceUpdateClinicPhysicalAddressBody';
export type { OrgStructureCommandServiceUpdateDepartmentDetailsBody } from './models/OrgStructureCommandServiceUpdateDepartmentDetailsBody';
export type { OrgStructureCommandServiceUpdateOrganizationDetailsBody } from './models/OrgStructureCommandServiceUpdateOrganizationDetailsBody';
export type { OrgStructureCommandServiceUpdateOrganizationLegalAddressBody } from './models/OrgStructureCommandServiceUpdateOrganizationLegalAddressBody';
export { queryAnnouncementV1AnnouncementPriority } from './models/queryAnnouncementV1AnnouncementPriority';
export { queryIncidentV1IncidentPriority } from './models/queryIncidentV1IncidentPriority';
export { queryIncidentV1IncidentStatus } from './models/queryIncidentV1IncidentStatus';
export type { queryIncidentV1StatusHistoryEntry } from './models/queryIncidentV1StatusHistoryEntry';
export type { queryRequestV1StatusHistoryEntry } from './models/queryRequestV1StatusHistoryEntry';
export type { RequestClassifierCommandServiceCreateRequestTypeBody } from './models/RequestClassifierCommandServiceCreateRequestTypeBody';
export type { RequestClassifierCommandServiceUpdateRequestTypeDetailsBody } from './models/RequestClassifierCommandServiceUpdateRequestTypeDetailsBody';
export type { ServiceRequestCommandServiceAssignExecutorsBody } from './models/ServiceRequestCommandServiceAssignExecutorsBody';
export type { ServiceRequestCommandServiceUpdateServiceRequestDescriptionBody } from './models/ServiceRequestCommandServiceUpdateServiceRequestDescriptionBody';
export type { ServiceRequestCommandServiceUpdateServiceRequestStatusBody } from './models/ServiceRequestCommandServiceUpdateServiceRequestStatusBody';
export type { v1ActorView } from './models/v1ActorView';
export type { v1Address } from './models/v1Address';
export type { v1AddressInput } from './models/v1AddressInput';
export type { v1AllowIncidentTypeForPatientsResponse } from './models/v1AllowIncidentTypeForPatientsResponse';
export type { v1AnnouncementView } from './models/v1AnnouncementView';
export type { v1ArchiveAnnouncementResponse } from './models/v1ArchiveAnnouncementResponse';
export type { v1AssignClinicHeadDeputyResponse } from './models/v1AssignClinicHeadDeputyResponse';
export type { v1AssignClinicHeadResponse } from './models/v1AssignClinicHeadResponse';
export type { v1AssignDepartmentResponsibleDeputyResponse } from './models/v1AssignDepartmentResponsibleDeputyResponse';
export type { v1AssignDepartmentResponsibleResponse } from './models/v1AssignDepartmentResponsibleResponse';
export type { v1AssignExecutorsResponse } from './models/v1AssignExecutorsResponse';
export type { v1AssignOrganizationAdminDeputyResponse } from './models/v1AssignOrganizationAdminDeputyResponse';
export type { v1AssignOrganizationAdminResponse } from './models/v1AssignOrganizationAdminResponse';
export type { v1AssignOrganizationDispatcherDeputyResponse } from './models/v1AssignOrganizationDispatcherDeputyResponse';
export type { v1AssignOrganizationDispatcherResponse } from './models/v1AssignOrganizationDispatcherResponse';
export type { v1AssignOrganizationHeadDeputyResponse } from './models/v1AssignOrganizationHeadDeputyResponse';
export type { v1AssignOrganizationHeadResponse } from './models/v1AssignOrganizationHeadResponse';
export type { v1BufferEntryView } from './models/v1BufferEntryView';
export { v1BufferStatus } from './models/v1BufferStatus';
export type { v1CancelIncidentResponse } from './models/v1CancelIncidentResponse';
export type { v1CancelPatientIncidentResponse } from './models/v1CancelPatientIncidentResponse';
export type { v1CancelScheduledVacationResponse } from './models/v1CancelScheduledVacationResponse';
export type { v1Category } from './models/v1Category';
export type { v1CategoryCount } from './models/v1CategoryCount';
export type { v1Clinic } from './models/v1Clinic';
export type { v1ClinicListItem } from './models/v1ClinicListItem';
export type { v1ClinicStats } from './models/v1ClinicStats';
export type { v1CountClinicsByOrganizationResponse } from './models/v1CountClinicsByOrganizationResponse';
export type { v1CountDepartmentsByClinicResponse } from './models/v1CountDepartmentsByClinicResponse';
export type { v1CountEmployeesByClinicResponse } from './models/v1CountEmployeesByClinicResponse';
export type { v1CountEmployeesByDepartmentResponse } from './models/v1CountEmployeesByDepartmentResponse';
export type { v1CountEmployeesByOrganizationResponse } from './models/v1CountEmployeesByOrganizationResponse';
export type { v1CountOrganizationsResponse } from './models/v1CountOrganizationsResponse';
export type { v1CountVacationsByEmployeeResponse } from './models/v1CountVacationsByEmployeeResponse';
export type { v1CreateAnnouncementRequest } from './models/v1CreateAnnouncementRequest';
export type { v1CreateAnnouncementResponse } from './models/v1CreateAnnouncementResponse';
export type { v1CreateClinicResponse } from './models/v1CreateClinicResponse';
export type { v1CreateDepartmentResponse } from './models/v1CreateDepartmentResponse';
export type { v1CreateIncidentCategoryResponse } from './models/v1CreateIncidentCategoryResponse';
export type { v1CreateIncidentRequest } from './models/v1CreateIncidentRequest';
export type { v1CreateIncidentResponse } from './models/v1CreateIncidentResponse';
export type { v1CreateIncidentTypeResponse } from './models/v1CreateIncidentTypeResponse';
export type { v1CreateOrganizationRequest } from './models/v1CreateOrganizationRequest';
export type { v1CreateOrganizationResponse } from './models/v1CreateOrganizationResponse';
export type { v1CreateRequestTypeResponse } from './models/v1CreateRequestTypeResponse';
export type { v1CreateServiceRequestRequest } from './models/v1CreateServiceRequestRequest';
export type { v1CreateServiceRequestResponse } from './models/v1CreateServiceRequestResponse';
export type { v1DeactivateIncidentCategoryResponse } from './models/v1DeactivateIncidentCategoryResponse';
export type { v1DeactivateIncidentTypeResponse } from './models/v1DeactivateIncidentTypeResponse';
export type { v1DeactivateRequestTypeResponse } from './models/v1DeactivateRequestTypeResponse';
export type { v1DeleteIncidentCategoryResponse } from './models/v1DeleteIncidentCategoryResponse';
export type { v1DeleteIncidentTypeResponse } from './models/v1DeleteIncidentTypeResponse';
export type { v1DeleteRequestTypeResponse } from './models/v1DeleteRequestTypeResponse';
export type { v1Department } from './models/v1Department';
export type { v1DepartmentCount } from './models/v1DepartmentCount';
export type { v1DepartmentListItem } from './models/v1DepartmentListItem';
export type { v1DepartmentStats } from './models/v1DepartmentStats';
export type { v1DisallowIncidentTypeForPatientsResponse } from './models/v1DisallowIncidentTypeForPatientsResponse';
export type { v1EmployeeCardView } from './models/v1EmployeeCardView';
export type { v1ErrorResponse } from './models/v1ErrorResponse';
export type { v1Executor } from './models/v1Executor';
export type { v1ExecutorHistoryEntry } from './models/v1ExecutorHistoryEntry';
export type { v1ForceEndVacationResponse } from './models/v1ForceEndVacationResponse';
export type { v1GetAnnouncementResponse } from './models/v1GetAnnouncementResponse';
export type { v1GetBufferEntryResponse } from './models/v1GetBufferEntryResponse';
export type { v1GetCategoryResponse } from './models/v1GetCategoryResponse';
export type { v1GetClinicHeadResponse } from './models/v1GetClinicHeadResponse';
export type { v1GetClinicResponse } from './models/v1GetClinicResponse';
export type { v1GetClinicStatsResponse } from './models/v1GetClinicStatsResponse';
export type { v1GetDepartmentResponse } from './models/v1GetDepartmentResponse';
export type { v1GetDepartmentResponsibleResponse } from './models/v1GetDepartmentResponsibleResponse';
export type { v1GetDepartmentStatsResponse } from './models/v1GetDepartmentStatsResponse';
export type { v1GetEmployeeResponse } from './models/v1GetEmployeeResponse';
export type { v1GetIncidentHistoryResponse } from './models/v1GetIncidentHistoryResponse';
export type { v1GetIncidentResponse } from './models/v1GetIncidentResponse';
export type { v1GetMyClinicRoleResponse } from './models/v1GetMyClinicRoleResponse';
export type { v1GetMyDepartmentRoleResponse } from './models/v1GetMyDepartmentRoleResponse';
export type { v1GetMyEmploymentResponse } from './models/v1GetMyEmploymentResponse';
export type { v1GetMyIdentityResponse } from './models/v1GetMyIdentityResponse';
export type { v1GetMyOrganizationRoleResponse } from './models/v1GetMyOrganizationRoleResponse';
export type { v1GetOrganizationResponse } from './models/v1GetOrganizationResponse';
export type { v1GetOrganizationStatsResponse } from './models/v1GetOrganizationStatsResponse';
export type { v1GetRequestTypeResponse } from './models/v1GetRequestTypeResponse';
export type { v1GetServiceRequestHistoryResponse } from './models/v1GetServiceRequestHistoryResponse';
export type { v1GetServiceRequestResponse } from './models/v1GetServiceRequestResponse';
export type { v1GetSnapshotResponse } from './models/v1GetSnapshotResponse';
export type { v1GetSummaryResponse } from './models/v1GetSummaryResponse';
export type { v1GetTimeSeriesResponse } from './models/v1GetTimeSeriesResponse';
export type { v1GetTypeResponse } from './models/v1GetTypeResponse';
export type { v1GrantSystemAdminRequest } from './models/v1GrantSystemAdminRequest';
export type { v1GrantSystemAdminResponse } from './models/v1GrantSystemAdminResponse';
export type { v1HireEmployeeRequest } from './models/v1HireEmployeeRequest';
export type { v1HireEmployeeResponse } from './models/v1HireEmployeeResponse';
export type { v1IncidentPriorityBreakdown } from './models/v1IncidentPriorityBreakdown';
export type { v1IncidentSourceBreakdown } from './models/v1IncidentSourceBreakdown';
export type { v1IncidentStatusBreakdown } from './models/v1IncidentStatusBreakdown';
export type { v1IncidentSummary } from './models/v1IncidentSummary';
export type { v1IncidentView } from './models/v1IncidentView';
export type { v1ListActiveRequestTypesByOrganizationResponse } from './models/v1ListActiveRequestTypesByOrganizationResponse';
export type { v1ListActiveRootCategoriesResponse } from './models/v1ListActiveRootCategoriesResponse';
export type { v1ListActiveTypesByOrganizationResponse } from './models/v1ListActiveTypesByOrganizationResponse';
export type { v1ListAnnouncementsForClinicResponse } from './models/v1ListAnnouncementsForClinicResponse';
export type { v1ListAnnouncementsForDepartmentResponse } from './models/v1ListAnnouncementsForDepartmentResponse';
export type { v1ListAnnouncementsForOrganizationResponse } from './models/v1ListAnnouncementsForOrganizationResponse';
export type { v1ListBufferEntriesResponse } from './models/v1ListBufferEntriesResponse';
export type { v1ListCategoriesByOrganizationResponse } from './models/v1ListCategoriesByOrganizationResponse';
export type { v1ListCategorySubtreeResponse } from './models/v1ListCategorySubtreeResponse';
export type { v1ListClinicsByOrganizationResponse } from './models/v1ListClinicsByOrganizationResponse';
export type { v1ListDepartmentsByClinicResponse } from './models/v1ListDepartmentsByClinicResponse';
export type { v1ListEmployeesByClinicResponse } from './models/v1ListEmployeesByClinicResponse';
export type { v1ListEmployeesByDepartmentResponse } from './models/v1ListEmployeesByDepartmentResponse';
export type { v1ListEmployeesByOrganizationResponse } from './models/v1ListEmployeesByOrganizationResponse';
export type { v1ListIncidentsResponse } from './models/v1ListIncidentsResponse';
export type { v1ListMyBufferEntriesResponse } from './models/v1ListMyBufferEntriesResponse';
export type { v1ListMyIncidentsResponse } from './models/v1ListMyIncidentsResponse';
export type { v1ListMyOrganizationsResponse } from './models/v1ListMyOrganizationsResponse';
export type { v1ListOrgAdminsResponse } from './models/v1ListOrgAdminsResponse';
export type { v1ListOrganizationsResponse } from './models/v1ListOrganizationsResponse';
export type { v1ListOrgDispatchersResponse } from './models/v1ListOrgDispatchersResponse';
export type { v1ListOrgHeadsResponse } from './models/v1ListOrgHeadsResponse';
export type { v1ListPatientAllowedTypesByOrganizationResponse } from './models/v1ListPatientAllowedTypesByOrganizationResponse';
export type { v1ListPatientVisibleCategoriesByOrganizationResponse } from './models/v1ListPatientVisibleCategoriesByOrganizationResponse';
export type { v1ListRequestTypesByOrganizationResponse } from './models/v1ListRequestTypesByOrganizationResponse';
export type { v1ListServiceRequestsByIncidentResponse } from './models/v1ListServiceRequestsByIncidentResponse';
export type { v1ListServiceRequestsResponse } from './models/v1ListServiceRequestsResponse';
export type { v1ListSystemAdminsResponse } from './models/v1ListSystemAdminsResponse';
export type { v1ListTypesByCategoryResponse } from './models/v1ListTypesByCategoryResponse';
export type { v1ListVacationsByEmployeeResponse } from './models/v1ListVacationsByEmployeeResponse';
export type { v1MoveIncidentCategoryResponse } from './models/v1MoveIncidentCategoryResponse';
export type { v1MoveIncidentTypeResponse } from './models/v1MoveIncidentTypeResponse';
export type { v1Organization } from './models/v1Organization';
export type { v1OrganizationListItem } from './models/v1OrganizationListItem';
export type { v1OrganizationStats } from './models/v1OrganizationStats';
export type { v1PatientBufferStatusBreakdown } from './models/v1PatientBufferStatusBreakdown';
export type { v1PatientBufferSummary } from './models/v1PatientBufferSummary';
export { v1PatientStatus } from './models/v1PatientStatus';
export type { v1Point } from './models/v1Point';
export type { v1PointInput } from './models/v1PointInput';
export type { v1PriorityHistoryEntry } from './models/v1PriorityHistoryEntry';
export type { v1PublishPatientIncidentResponse } from './models/v1PublishPatientIncidentResponse';
export type { v1ReactivateIncidentCategoryResponse } from './models/v1ReactivateIncidentCategoryResponse';
export type { v1ReactivateIncidentTypeResponse } from './models/v1ReactivateIncidentTypeResponse';
export type { v1ReactivateRequestTypeResponse } from './models/v1ReactivateRequestTypeResponse';
export type { v1RegistrarView } from './models/v1RegistrarView';
export type { v1RejectPatientIncidentResponse } from './models/v1RejectPatientIncidentResponse';
export type { v1RemoveClinicHeadDeputyResponse } from './models/v1RemoveClinicHeadDeputyResponse';
export type { v1RemoveDepartmentResponsibleDeputyResponse } from './models/v1RemoveDepartmentResponsibleDeputyResponse';
export type { v1RemoveOrganizationAdminDeputyResponse } from './models/v1RemoveOrganizationAdminDeputyResponse';
export type { v1RemoveOrganizationDispatcherDeputyResponse } from './models/v1RemoveOrganizationDispatcherDeputyResponse';
export type { v1RemoveOrganizationHeadDeputyResponse } from './models/v1RemoveOrganizationHeadDeputyResponse';
export type { v1ReopenIncidentResponse } from './models/v1ReopenIncidentResponse';
export type { v1RequestStatusBreakdown } from './models/v1RequestStatusBreakdown';
export type { v1RequestSummary } from './models/v1RequestSummary';
export type { v1RequestType } from './models/v1RequestType';
export type { v1ResolutionStats } from './models/v1ResolutionStats';
export type { v1RevokeClinicHeadResponse } from './models/v1RevokeClinicHeadResponse';
export type { v1RevokeDepartmentResponsibleResponse } from './models/v1RevokeDepartmentResponsibleResponse';
export type { v1RevokeOrganizationAdminResponse } from './models/v1RevokeOrganizationAdminResponse';
export type { v1RevokeOrganizationDispatcherResponse } from './models/v1RevokeOrganizationDispatcherResponse';
export type { v1RevokeOrganizationHeadResponse } from './models/v1RevokeOrganizationHeadResponse';
export type { v1RevokeSystemAdminResponse } from './models/v1RevokeSystemAdminResponse';
export type { v1RoleAssignment } from './models/v1RoleAssignment';
export type { v1ScheduleVacationResponse } from './models/v1ScheduleVacationResponse';
export type { v1SearchEmployeesByOrganizationResponse } from './models/v1SearchEmployeesByOrganizationResponse';
export type { v1SearchOrganizationsResponse } from './models/v1SearchOrganizationsResponse';
export type { v1ServiceRequest } from './models/v1ServiceRequest';
export type { v1SnapshotIncident } from './models/v1SnapshotIncident';
export type { v1SnapshotPatientBuffer } from './models/v1SnapshotPatientBuffer';
export type { v1SnapshotRequest } from './models/v1SnapshotRequest';
export type { v1StartVacationNowResponse } from './models/v1StartVacationNowResponse';
export type { v1SubmitPatientIncidentRequest } from './models/v1SubmitPatientIncidentRequest';
export type { v1SubmitPatientIncidentResponse } from './models/v1SubmitPatientIncidentResponse';
export type { v1SummaryPeriod } from './models/v1SummaryPeriod';
export type { v1SystemAdminView } from './models/v1SystemAdminView';
export type { v1TerminateEmployeeResponse } from './models/v1TerminateEmployeeResponse';
export type { v1TimeSeriesBucket } from './models/v1TimeSeriesBucket';
export { v1TimeSeriesGranularity } from './models/v1TimeSeriesGranularity';
export type { v1TimeSeriesIncidentBucket } from './models/v1TimeSeriesIncidentBucket';
export type { v1TimeSeriesRequestBucket } from './models/v1TimeSeriesRequestBucket';
export type { v1TypeCount } from './models/v1TypeCount';
export type { v1UnarchiveAnnouncementResponse } from './models/v1UnarchiveAnnouncementResponse';
export type { v1UpdateAnnouncementPriorityResponse } from './models/v1UpdateAnnouncementPriorityResponse';
export type { v1UpdateAnnouncementResponse } from './models/v1UpdateAnnouncementResponse';
export type { v1UpdateClinicDetailsResponse } from './models/v1UpdateClinicDetailsResponse';
export type { v1UpdateClinicPhysicalAddressResponse } from './models/v1UpdateClinicPhysicalAddressResponse';
export type { v1UpdateDepartmentDetailsResponse } from './models/v1UpdateDepartmentDetailsResponse';
export type { v1UpdateEmployeeDepartmentResponse } from './models/v1UpdateEmployeeDepartmentResponse';
export type { v1UpdateEmployeePositionResponse } from './models/v1UpdateEmployeePositionResponse';
export type { v1UpdateIncidentCategoryDetailsResponse } from './models/v1UpdateIncidentCategoryDetailsResponse';
export type { v1UpdateIncidentDescriptionResponse } from './models/v1UpdateIncidentDescriptionResponse';
export type { v1UpdateIncidentPriorityResponse } from './models/v1UpdateIncidentPriorityResponse';
export type { v1UpdateIncidentStatusResponse } from './models/v1UpdateIncidentStatusResponse';
export type { v1UpdateIncidentTypeDetailsResponse } from './models/v1UpdateIncidentTypeDetailsResponse';
export type { v1UpdateOrganizationDetailsResponse } from './models/v1UpdateOrganizationDetailsResponse';
export type { v1UpdateOrganizationLegalAddressResponse } from './models/v1UpdateOrganizationLegalAddressResponse';
export type { v1UpdatePatientIncidentResponse } from './models/v1UpdatePatientIncidentResponse';
export type { v1UpdateRequestTypeDetailsResponse } from './models/v1UpdateRequestTypeDetailsResponse';
export type { v1UpdateServiceRequestDescriptionResponse } from './models/v1UpdateServiceRequestDescriptionResponse';
export type { v1UpdateServiceRequestStatusResponse } from './models/v1UpdateServiceRequestStatusResponse';
export type { v1UpdateVacationEndDateResponse } from './models/v1UpdateVacationEndDateResponse';
export type { v1VacationView } from './models/v1VacationView';
export type { v1ValidationFailedDetails } from './models/v1ValidationFailedDetails';
export type { ValidationFailedDetailsFieldViolation } from './models/ValidationFailedDetailsFieldViolation';

export { AnalyticsQueryService } from './services/AnalyticsQueryService';
export { AnnouncementCommandService } from './services/AnnouncementCommandService';
export { AnnouncementQueryService } from './services/AnnouncementQueryService';
export { IncidentBufferCommandService } from './services/IncidentBufferCommandService';
export { IncidentClassifierCommandService } from './services/IncidentClassifierCommandService';
export { IncidentClassifierQueryService } from './services/IncidentClassifierQueryService';
export { IncidentCommandService } from './services/IncidentCommandService';
export { IncidentQueryService } from './services/IncidentQueryService';
export { MembershipCommandService } from './services/MembershipCommandService';
export { MembershipQueryService } from './services/MembershipQueryService';
export { OrgStructureCommandService } from './services/OrgStructureCommandService';
export { OrgStructureQueryService } from './services/OrgStructureQueryService';
export { RequestClassifierCommandService } from './services/RequestClassifierCommandService';
export { RequestClassifierQueryService } from './services/RequestClassifierQueryService';
export { SelfQueryService } from './services/SelfQueryService';
export { ServiceRequestCommandService } from './services/ServiceRequestCommandService';
export { ServiceRequestQueryService } from './services/ServiceRequestQueryService';
export { StatsQueryService } from './services/StatsQueryService';
