/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * NotificationType enumerates all notification types.
 *
 * - NOTIFICATION_TYPE_INCIDENT_CREATED: Incident
 * - NOTIFICATION_TYPE_SERVICE_REQUEST_CREATED: Service request
 * - NOTIFICATION_TYPE_VACATION_SCHEDULED: Vacation
 * - NOTIFICATION_TYPE_EMPLOYEE_HIRED: Employee
 * - NOTIFICATION_TYPE_ROLE_ASSIGNED: Role
 * - NOTIFICATION_TYPE_SYSTEM_ADMIN_GRANTED: System admin
 * - NOTIFICATION_TYPE_SECURITY_NEW_LOGIN: Security (bypass quiet hours)
 */
export enum v1NotificationType {
    NOTIFICATION_TYPE_UNSPECIFIED = 'NOTIFICATION_TYPE_UNSPECIFIED',
    NOTIFICATION_TYPE_INCIDENT_CREATED = 'NOTIFICATION_TYPE_INCIDENT_CREATED',
    NOTIFICATION_TYPE_INCIDENT_STATUS_CHANGED = 'NOTIFICATION_TYPE_INCIDENT_STATUS_CHANGED',
    NOTIFICATION_TYPE_INCIDENT_PRIORITY_CHANGED = 'NOTIFICATION_TYPE_INCIDENT_PRIORITY_CHANGED',
    NOTIFICATION_TYPE_INCIDENT_DESCRIPTION_UPDATED = 'NOTIFICATION_TYPE_INCIDENT_DESCRIPTION_UPDATED',
    NOTIFICATION_TYPE_SERVICE_REQUEST_CREATED = 'NOTIFICATION_TYPE_SERVICE_REQUEST_CREATED',
    NOTIFICATION_TYPE_SERVICE_REQUEST_STATUS_CHANGED = 'NOTIFICATION_TYPE_SERVICE_REQUEST_STATUS_CHANGED',
    NOTIFICATION_TYPE_SERVICE_REQUEST_EXECUTOR_ASSIGNED = 'NOTIFICATION_TYPE_SERVICE_REQUEST_EXECUTOR_ASSIGNED',
    NOTIFICATION_TYPE_SERVICE_REQUEST_EXECUTOR_REMOVED = 'NOTIFICATION_TYPE_SERVICE_REQUEST_EXECUTOR_REMOVED',
    NOTIFICATION_TYPE_VACATION_SCHEDULED = 'NOTIFICATION_TYPE_VACATION_SCHEDULED',
    NOTIFICATION_TYPE_VACATION_STARTED = 'NOTIFICATION_TYPE_VACATION_STARTED',
    NOTIFICATION_TYPE_VACATION_ENDED = 'NOTIFICATION_TYPE_VACATION_ENDED',
    NOTIFICATION_TYPE_VACATION_CANCELLED = 'NOTIFICATION_TYPE_VACATION_CANCELLED',
    NOTIFICATION_TYPE_VACATION_END_DATE_CHANGED = 'NOTIFICATION_TYPE_VACATION_END_DATE_CHANGED',
    NOTIFICATION_TYPE_EMPLOYEE_HIRED = 'NOTIFICATION_TYPE_EMPLOYEE_HIRED',
    NOTIFICATION_TYPE_EMPLOYEE_TERMINATED = 'NOTIFICATION_TYPE_EMPLOYEE_TERMINATED',
    NOTIFICATION_TYPE_EMPLOYEE_DEPARTMENT_CHANGED = 'NOTIFICATION_TYPE_EMPLOYEE_DEPARTMENT_CHANGED',
    NOTIFICATION_TYPE_EMPLOYEE_POSITION_CHANGED = 'NOTIFICATION_TYPE_EMPLOYEE_POSITION_CHANGED',
    NOTIFICATION_TYPE_ROLE_ASSIGNED = 'NOTIFICATION_TYPE_ROLE_ASSIGNED',
    NOTIFICATION_TYPE_ROLE_REVOKED = 'NOTIFICATION_TYPE_ROLE_REVOKED',
    NOTIFICATION_TYPE_SYSTEM_ADMIN_GRANTED = 'NOTIFICATION_TYPE_SYSTEM_ADMIN_GRANTED',
    NOTIFICATION_TYPE_SYSTEM_ADMIN_REVOKED = 'NOTIFICATION_TYPE_SYSTEM_ADMIN_REVOKED',
    NOTIFICATION_TYPE_SECURITY_NEW_LOGIN = 'NOTIFICATION_TYPE_SECURITY_NEW_LOGIN',
    NOTIFICATION_TYPE_SECURITY_EMAIL_CHANGED = 'NOTIFICATION_TYPE_SECURITY_EMAIL_CHANGED',
}
